### ISSUE TITLE
Wrong/missing build-dependencies 

### ISSUE THREAD

**Issue by vittali** [vittali/embedded-library#1]
When running ./gradlew check , I get:

```
softbrix.emblib.test.use.TestImpl STANDARD_ERROR
    -----------------
    Errors
    000: Cannot find /error/org.apache.felix.framework;version=5.6 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    001: Cannot find /error/slf4j.api;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    002: Cannot find /error/aQute.libg;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    003: Cannot find /error/biz.aQute.bndlib;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    004: Cannot find /error/osgi.annotation;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    005: Cannot find /error/osgi.cmpn;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    006: Cannot find /error/osgi.core;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    007: Cannot find /error/slf4j.simple;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    008: org.apache.felix.framework;version=5.6 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    009: slf4j.api;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    010: aQute.libg;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    011: biz.aQute.bndlib;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    012: osgi.annotation;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    013: osgi.cmpn;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    014: osgi.core;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
    015: slf4j.simple;version=0 Not found in [bnd-cache, /home/p/Downloads/embedded-library/cnf/nonosgi-repo r/w=true]
Gradle Test Executor 1 finished executing tests.

softbrix.emblib.test.use.TestImpl > classMethod FAILED
    softbrix.lib.type.common.Bug: project check yielded false for project softbrix.emblib.test.use
        at softbrix.lib.type.common.Bug.error(Bug.java:11)
        at softbrix.lib.type.result.R.failure(R.java:29)
        at softbrix.lib.type.result.R$Failure.flatMap(R.java:106)
        at softbrix.fw.lib.FW.mk(FW.java:94)
        at softbrix.emblib.test.use.TestImpl.before(TestImpl.java:16)
...
```

When I add `biz.aQute.bnd-3.3.0.jar` to the buildpath, the test pass, but the operation is very slow ( ~ 6 seconds, perhaps something gets downloaded ? )

**Comment by vittali** [comment]
Missing dependencies added: biz.aQute.repository, biz.aQute.resolve.
